# Generated by Django 4.1 on 2022-09-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backUpPerson',
            fields=[
                ('CF_BC_person', models.CharField(max_length=300)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('cognome', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='degrees',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='dipendenti_user',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('cognome', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('dataNascita', models.CharField(max_length=300)),
                ('birthplace', models.CharField(max_length=300)),
                ('nazionalita', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('psw', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='esperienze',
            fields=[
                ('workerId', models.PositiveIntegerField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('azienda', models.CharField(max_length=300)),
                ('periodo', models.CharField(max_length=300)),
                ('duties', models.CharField(max_length=300)),
                ('luogo', models.CharField(max_length=300)),
                ('payment', models.CharField(max_length=300)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('organization', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=300)),
                ('jobType', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('minimumQualifications', models.TextField()),
                ('preferredQualifications', models.TextField()),
                ('description', models.TextField()),
                ('dateAdded', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='spotlights',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('CF', models.CharField(max_length=300)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('cognome', models.CharField(max_length=300)),
                ('dataNascita', models.CharField(max_length=300)),
                ('birthplace', models.CharField(max_length=300)),
                ('nazionalita', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('jobType', models.CharField(max_length=300)),
                ('period', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('languages', models.CharField(max_length=300)),
                ('patenta', models.CharField(max_length=300)),
                ('car', models.CharField(max_length=300)),
                ('qualification', models.CharField(max_length=300)),
            ],
        ),
    ]
