# Generated by Django 4.1 on 2022-09-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupperson',
            options={'managed': True},
        ),
    ]
