# Generated by Django 4.1 on 2022-09-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperienze',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
