# Generated by Django 4.1 on 2022-09-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0002_alter_esperienze_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupperson',
            name='workerId',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupperson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
