# Generated by Django 4.1 on 2022-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_backupperson_workerid_alter_backupperson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
