# Generated by Django 4.1 on 2022-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0004_alter_jobs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
